module.exports = {

  // --- OTHER ---

  githubTokenWarn: false, // Suppress missing GitHub Token error, harmless cause we are not on GitHub platform

  // --- CONNECTION ---

  platform: 'github',

  //persistRepoData: true, // Not useful in pipeline where instance is destroyed on each run
  enabled: false,
  
  //Skips a lot faster a repo if it doesn't contain an enabled renovate.json5 config file
  optimizeForDisabled: true,

  // --- RENOVATE WELCOMING ---

  autodiscover: false,
  repositories: ["danne-jm/demo-migrations"],

  // Don't force renovate config file creation PRs on repos missing it
  onboarding: false,

  dryRun: 'full', 
  
  // Require some kind of config from repository
  requireConfig: "required",

  // if a PR was closed, Renovate won't remember this and remakes the PR on the next run. Azure doesn't support Renovate Dashboard via Issues, so this makes it easier in case you do close something and regret it
  recreateWhen: 'always',
  additionalBranchPrefix: "{{{semanticCommitType}}}/",
  branchName: "{{{branchPrefix}}}{{{additionalBranchPrefix}}}{{{branchTopic}}}", //renovate/fix/other-minor-patch

  prFooter: `<br>

*This PR was auto-generated by [Renovate Bot](https://google.com)* on ***${new Date().toLocaleString("fr-BE", {timeZone: "Europe/Brussels"})}***
`,

  packageRules: [  
      {  
        matchPackageNames: ["docker"],  
        enabled: false  
      },  
      {  
        matchPackagePrefixes: ["docker"],  
        enabled: false  
      },  
      {  
        matchFileNames: ["Dockerfile", "docker-compose.yml"],  
        enabled: false  
      },
    ],
  
  allowedPostUpgradeCommands: [".*"],
  postUpgradeTasks: {
    commands: [
       "WORKSPACE_DIR={{{repositoryPath}}} RENOVATE_UPDATED_PACKAGE={{{depName}}} RENOVATE_OLD_VERSION={{{currentVersion}}} RENOVATE_NEW_VERSION={{{newVersion}}} bash renovate/scripts/post-upgrade.sh"
    ],
    fileFilters: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"],
    executionMode: "branch"
  }
};